contacts/__init__.py
import json
import logging

logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.DEBUG,
    )
logger = logging.getLogger(__name__)

from flask import Flask

# from authlib.integrations.flask_client import OAuth, OAuthError
# from flask_debugtoolbar import DebugToolbarExtension

app = Flask(__name__, instance_relative_config=True)
app.config.from_object('contacts.default_config')
app.config.from_envvar('SIM_CONTACTS_SETTINGS', silent=True)
app.config.from_pyfile('config.py')

app.secret_key = app.config.get('SECRET_KEY', "DEV TESTING")
if app.secret_key == "DEV TESTING":
    app.logger.warn("WARNING: Set a secret key!!!")

# toolbar = DebugToolbarExtension(app)

from .views import views
from .api import api

app.register_blueprint(api, url_prefix="/api")
app.register_blueprint(views, url_prefix="")

# @app.before_first_request
def print_url_map():
    app.logger.debug("URL map:")
    for rule in app.url_map.iter_rules():
        app.logger.debug(rule)

# @app.before_first_request
def prime_edits():
    from .model import db, Contact, Edit
    db.create_all()
    edit_count = Edit.query.count()
    app.logger.info("Edit count: {}".format(edit_count))
    if edit_count == 0:
        app.logger.info("LOADING EDIT BASELINE")
        for contact in Contact.query.all():
            edit = Edit(
                    subject_type='Contact',
                    subject_id=contact.id,
                    after=json.dumps(contact.as_dict(tags=True)),
                    user='SYSTEM'
                    )
            db.session.add(edit)
        rows = db.session.commit()
        app.logger.info("SAVED {} rows".format(rows))

with app.app_context():
    prime_edits()

contacts/auth.py
import traceback
from functools import wraps
import hashlib
import time

from authlib.integrations.flask_client import OAuth, OAuthError
from flask import *

from . import app

oauth = OAuth(app)

# https://flask-oauthlib.readthedocs.io/en/latest/client.html#facebook-oauth
facebook = oauth.register('facebook',
    # request_token_url=None,
    client_id=app.config['FACEBOOK_APP_ID'],
    client_secret=app.config['FACEBOOK_APP_SECRET'],
    request_token_params={'scope': 'email'},
    access_token_params={'scope': 'email'},

    api_base_url= 'https://graph.facebook.com/v7.0/',
    access_token_url= 'https://graph.facebook.com/v7.0/oauth/access_token',
    authorize_url= 'https://www.facebook.com/v7.0/dialog/oauth',
    client_kwargs= {'scope': 'email public_profile'},
    # userinfo_endpoint= USERINFO_ENDPOINT,

)
facebook = oauth.create_client('facebook')

@app.context_processor
def context():
    logged_in = False
    try:
        logged_in = 'me' in session or g.user
    except:
        pass

    return dict(logged_in=logged_in, timestamp=time.time())

'''
# https://flask-oauthlib.readthedocs.io/en/latest/client.html#signing-in-authorizing
@facebook.tokengetter
def get_facebook_token(token=None):
    return session.get('oauth_token')
'''

@app.route('/login')
def login():
    try:
        scheme = app.config['PREFERRED_URL_SCHEME'] or 'http'
    except:
        app.logger.error("Error determining URL scheme")
        scheme = "http"
        traceback.print_exc()
    app.logger.info("URL scheme is {}".format(scheme))
    callback_url = url_for(
        'oauth_authorized',
        next=request.args.get('next') or request.referrer or None,
        _scheme=scheme,
        _external=True
    )
    return facebook.authorize_redirect(callback_url)

@app.route('/logout')
def logout():
    if 'user' in g:
        del g.user
    if 'me' in session:
        del session['me']
    return redirect('/')


@app.route('/oauth-authorized')
def oauth_authorized():
    next_url = request.args.get('next') or url_for('index')
    resp = facebook.authorize_access_token()

    if resp is None:
        flash('You denied the request to sign in.')
        return redirect(next_url)

    if isinstance(resp, OAuthError):
        return 'Access denied: %s' % resp.message

    session['oauth_token'] = (resp['access_token'], '')
    me = facebook.get('/me/?fields=email,name,id,picture.height(50).width(50),first_name,last_name')

    user = me.json()
    email = user['email'].strip().lower()

    if email not in app.config['ALLOWED_USERS']:
        flash("You are not one of the allowed users.  Please ask an admin for access.")
        return logout()

    g.user = user
    session['me'] = user
    try:
        session['picture_url'] = user['picture']['data']['url']
    except KeyError:
        session['picture_url'] = "https://www.gravatar.com/avatar/{}".format(hashlib.md5(email).hexdigest())

    app.logger.info('Logged in as id={} name={} redirect={}'.format(
        user['id'], user['name'], request.args.get('next')))
    flash('You were signed in as {} ({})'.format(user['name'], user['id']))
    return redirect(next_url)

def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        app.logger.debug("Checking for a login...")
        user = g.setdefault('user')
        if user is None:
            if 'me' in session and session['me']:
                # Legacy login, TODO remove
                g.user = session['me']
            else:
                app.logger.debug("No login.")
                return redirect(url_for('login', next=request.url))

        email = session['me']['email'].strip().lower()
        if email not in app.config['ALLOWED_USERS']:
            flash("You are not one of the allowed users.  Please ask an admin for access.")
            return logout()

        app.logger.debug("Login OK")
        return f(*args, **kwargs)
    return decorated_function

contacts/views.py
import pprint

from flask import *

from .auth import facebook, login_required

views = Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template('home.html.j2')

@views.route('/contact/new')
@login_required
def new_contact():
    return render_template('contact-new.html.j2')

@views.route('/contact/<contact_id>')
@login_required
def show_contact(contact_id):
    return render_template('contact-show.html.j2', contact_id=contact_id)

contacts/templates/contact-new.html.j2
{% extends "main.html.j2" %}
{% block content %}

{% if logged_in %}
<contact></contact>
{% else %}
<p>Not logged in.</p>
{% endif %}

{% endblock %}

contacts/templates/contact-show.html.j2
{% extends "main.html.j2" %}
{% block content %}

{% if logged_in %}
<contact id="{{contact_id}}"></contact>
{% else %}
<p>Not logged in.</p>
{% endif %}

{% endblock %}

contacts/templates/home.html.j2
{% extends "main.html.j2" %}
{% block content %}

{% if logged_in %}
<tags></tags>
<contacts tags="{{tags}}"></contacts>
{% else %}
<p>Not logged in.</p>
{% endif %}

{% if 'me' in session or g.user %}
<h2>Session</h2>
Here's what Facebook told us about you:
<dl>
{% for key in session['me'] %}
<dt>{{key | e}}</dt>
<dd>{{session['me'][key] | e}}</dd>
{% endfor %}
</dl>
{% endif %}

{% endblock %}

contacts/templates/main.html.j2
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <link rel="shortcut icon" type="image/png" href="/static/favicon.ico"/>
  <link rel="stylesheet" href="/static/app.css?t={{timestamp}}" type="text/css" charset="utf-8">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/loaders.css/0.1.2/loaders.min.css" integrity="sha256-T+5i0dKjbTyIP7aTCrF10Ey/Gk4WxQ7TVrkZoyg5mWQ=" crossorigin="anonymous" />
  <script src="https://unpkg.com/vue@2" type="text/javascript"></script>
  <script src="https://unpkg.com/vue-resource@1.3.1/dist/vue-resource.min.js" type="text/javascript"></script>
  <script type="text/javascript" src="/static/app.js?t={{timestamp}}"></script>
  <title>{% block title %}Contacts List{% endblock %}</title>
</head>

<body>
    <ul id="nav">
        <li><a href="{{url_for('views.home')}}">Contacts</a></li>
        <li>
            {% if 'me' in session or g.user %}

            <div id="user">
            Hi, {{ session['me']['first_name'] }}!
            {% if 'picture_url' in session %}
            <img src="{{session['picture_url']}}">
            <a href="{{ url_for('logout') }}">Log Out</a>
            </div>

            {% endif %}
            {% else %}

            <a href="{{ url_for('login') }}">Log in</a>

            {% endif %}
        </li>
        <li><a href="{{ url_for('views.new_contact') }}">New Contact</a></li>
    </ul>


    <div id="app">


{% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}

    {% block content %}
    <h1>Hello.</h1>

    This is the main (wrapper) template.  You should never see this on a real page,
    because all the other page templates should replace the 'content' block.

    {%- endblock %}
    </div>

    <script
         src="https://code.jquery.com/jquery-3.1.1.slim.min.js"
         integrity="sha256-/SIrNqv8h6QGKDuNoLGA4iret+kyesCkHGzVUUV0shc="
         crossorigin="anonymous"></script>
    <script>
Vue.app = new Vue({
    el: "#app"
});
    </script>
</body>
</html>